[package]
name = "bls-signatures"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
ff = "0.4"
rand = "0.4"
byteorder = "1.2"
failure = "0.1"
paired = "^0.15.0"

[features]
default = []

[package.metadata.release]
pre-release-commit-message = "chore(release): release {{version}}"
pro-release-commit-message = "chore(release): starting development cycle for {{next_version}}"
